### PR TITLE
[v2.0.3] Issue #3178 fixes

### LINKED ISSUE #3178: [SB] Add/Edit active task > Anchor date based > Select anchor date type dropdown > Previously selected value is displayed for the particular scenario
Steps
1. Create/Edit study
2. Navigate to the active tasks section
3. Create/Edit active task
4. Switch to the Schedule tab
5. Select the 'Anchor date based' radio button
6. Select any value from the dropdown click on save
7. Select the 'Select' value from the dropdown and click on the Save button 
8. Observe the value in the dropdown

AR : Previously selected value is displayed
ER : Previously selected value should not be displayed

https://user-images.githubusercontent.com/71445210/107756516-553cfd80-6d4a-11eb-8da2-d846007ae284.mp4

### PR DESCRIPTION
**Pull request by pujithr**
#3178: Dropdown value is corrected of previous selected one

### CODE REVIEW

File: study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java [hunk 1]
```diff
@@ -322,9 +322,7 @@ public ActiveTaskBo saveOrUpdateActiveTask(ActiveTaskBo activeTaskBo, String cus
         if (activeTaskBo.getScheduleType() != null) {
           addActiveTaskeBo.setScheduleType(activeTaskBo.getScheduleType());
         }
-        if (activeTaskBo.getAnchorDateId() != null) {
-          addActiveTaskeBo.setAnchorDateId(activeTaskBo.getAnchorDateId());
-        }
+        addActiveTaskeBo.setAnchorDateId(activeTaskBo.getAnchorDateId());
```
Comment (moschetti) [inline study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java:325]: Please update file copyright to add Google LLC & `2020-2021`

Comment (pujithr) [reply study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/service/StudyActiveTasksServiceImpl.java:326]: Updated copyright.

**Review by moschetti — APPROVED** [review]
